# Generated by Django 2.2.4 on 2019-08-04 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('CPF', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('endereço', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=70)),
                ('serie', models.CharField(choices=[('1º Ano - Fundamental I', '1º Ano - Fundamental I'), ('2º Ano - Fundamental I', '2º Ano - Fundamental I'), ('3º Ano - Fundamental I', '3º Ano - Fundamental I'), ('4º Ano - Fundamental I', '4º Ano - Fundamental I'), ('5º Ano - Fundamental I', '5º Ano - Fundamental I'), ('6º Ano - Fundamental II', '6º Ano - Fundamental II'), ('7º Ano - Fundamental II', '7º Ano - Fundamental II'), ('8º Ano - Fundamental II', '8º Ano - Fundamental II'), ('9º Ano - Fundamental II', '9º Ano - Fundamental II'), ('1º Ano - Médio', '1º Ano - Médio'), ('2º Ano - Médio', '1º Ano - Médio')], default='', max_length=50)),
                ('escola', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('necessidade_especial', models.BooleanField(default=False)),
                ('preco', models.IntegerField()),
                ('desconto', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Atrasado', 'Atrasado'), ('Pendente', 'Pendente')], default='', max_length=50)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente')),
            ],
        ),
    ]
