# Generated by Django 2.2.4 on 2019-12-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190804_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CPF',
            new_name='cpfCnpj',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereço',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.AddField(
            model_name='cliente',
            name='addressNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='mobilePhone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='postalCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
