# Generated by Django 2.2.4 on 2019-12-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20191229_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descricao_alunos',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
