# Generated by Django 2.2.4 on 2020-01-04 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20191230_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='status',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.CharField(max_length=50, verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='necessidade_especial',
            field=models.BooleanField(default=False, verbose_name='Necessidade Especial?'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(max_length=70, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações Gerais sobre o Aluno', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(choices=[('1º Ano - Fundamental I', '1º Ano - Fundamental I'), ('2º Ano - Fundamental I', '2º Ano - Fundamental I'), ('3º Ano - Fundamental I', '3º Ano - Fundamental I'), ('4º Ano - Fundamental I', '4º Ano - Fundamental I'), ('5º Ano - Fundamental I', '5º Ano - Fundamental I'), ('6º Ano - Fundamental II', '6º Ano - Fundamental II'), ('7º Ano - Fundamental II', '7º Ano - Fundamental II'), ('8º Ano - Fundamental II', '8º Ano - Fundamental II'), ('9º Ano - Fundamental II', '9º Ano - Fundamental II'), ('1º Ano - Médio', '1º Ano - Médio'), ('2º Ano - Médio', '2º Ano - Médio')], default='', max_length=50, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Turma', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='addressNumber',
            field=models.IntegerField(verbose_name='Número da Casa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpfCnpj',
            field=models.CharField(max_length=17, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descricao_alunos',
            field=models.TextField(help_text='Campo para utilizar para Cadastro de Aluno', verbose_name='Sobre os Alunos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(help_text='Utilizar um email válido', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mobilePhone',
            field=models.CharField(help_text='Utilize um número válido', max_length=50, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='postalCode',
            field=models.IntegerField(help_text='Utilize um CEP válido', verbose_name='CEP'),
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_matricula', models.FloatField(verbose_name='Preço da Matrícula')),
                ('preco_mensalidade', models.FloatField(verbose_name='Preço da Mensalidade')),
                ('vencimento', models.IntegerField(verbose_name='Vencimento')),
                ('matricula', models.BooleanField(verbose_name='MATR.')),
                ('feveveiro', models.BooleanField(verbose_name='FEV.')),
                ('marco', models.BooleanField(verbose_name='MAR.')),
                ('abril', models.BooleanField(verbose_name='ABR.')),
                ('maio', models.BooleanField(verbose_name='MAI.')),
                ('junho', models.BooleanField(verbose_name='JUN.')),
                ('julho', models.BooleanField(verbose_name='JUL.')),
                ('agosto', models.BooleanField(verbose_name='AGO.')),
                ('setembro', models.BooleanField(verbose_name='SET.')),
                ('outubro', models.BooleanField(verbose_name='OUT.')),
                ('novembro', models.BooleanField(verbose_name='NOV.')),
                ('dezembro', models.BooleanField(verbose_name='DEZ.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='financeiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.Financeiro', verbose_name='Cadastro Financeiro'),
            preserve_default=False,
        ),
    ]
