# Generated by Django 2.2.4 on 2020-01-05 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20200104_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome_aluno'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['cliente'], 'verbose_name': 'Cadastro Financeiro', 'verbose_name_plural': 'Cadastro Financeiro'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['nome_turma'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Turma', verbose_name='Turma'),
        ),
    ]
