# Generated by Django 2.2.4 on 2020-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20200105_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='matricula',
            field=models.CharField(choices=[('EM', 'EM'), ('PG', 'PG'), ('--', '--')], default='--', max_length=50, verbose_name='Série'),
        ),
    ]
