# Generated by Django 2.2.4 on 2020-01-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20200105_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='matricula',
            field=models.BooleanField(verbose_name='MATR.'),
        ),
    ]
